<?php
/**
 * @file
 * Contains Vantiv\Response;
 */

namespace Vantiv;

use Exception;

/**
 * Class Response
 * @package Vantiv
 *
 * Default Response class.
 */
class Response {

  protected $response = NULL;

  function __construct($response) {
    $this->response = json_decode($response);
  }

  /**
   * @return string The request ID generated by Vantiv for this request.
   */
  public function getRequestID() {
    return $this->response->RequestID;
  }

  public function success() {
    return $this->failure() == FALSE;
  }

  public function failure() {
    return isset($this->response->Error) ? $this->response->Error->Details : FALSE;
  }

  /**
   * @return stdClass The litleOnlineResponse from a Vantiv response.
   * @throws Exception.
   */
  public function getResponse() {
    if (!isset($this->response->litleOnlineResponse)) {
      var_dump($this->response);
      throw new Exception('litleOnlineResponse not found in this response. Request ID ' . $this->getRequestID());
    }
    return $this->response->litleOnlineResponse;
  }

}
