<?php
/**
 * @file
 * Contains Vantiv\Response;
 */

namespace Vantiv;

/**
 * Class Response
 * @package Vantiv
 *
 * Default Response class.
 */
class Response {

  protected $response = NULL;

  function __construct($response) {
    $this->response = json_decode($response);
  }

  /**
   * @return string The request ID generated by Vantiv for this request.
   */
  public function getRequestID() {
    return $this->response->RequestID;
  }

  /**
   * @return stdClass The litleOnlineResponse from a Vantiv response.
   */
  public function getResponse() {
    return $this->response->litleOnlineResponse;
  }

}
